# Generated by Django 5.2.14 on 2026-05-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dept', models.CharField(blank=True, max_length=50, null=True, verbose_name='Department')),
                ('spec', models.CharField(blank=True, max_length=100, null=True, verbose_name='Specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=100, verbose_name='Subject Title')),
                ('units', models.IntegerField(default=3)),
                ('days', models.CharField(max_length=50)),
                ('st', models.CharField(max_length=20)),
                ('et', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=50)),
                ('instId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.instructor')),
                ('secId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='scheduling.section')),
            ],
        ),
    ]
